name: Deploy Lambda with Image

on:
  workflow_call:
    inputs:
      aws_region:
        type: string
        required: true
        description: aws region to deploy app
    secrets:
      aws_assume_role:
        required: true
        description: aws role to assume
      image:
        type: string
        required: true
        description: ecr image to use in lambda function
      function_name:
        type: string
        required: true
        description: name of lambda function to update

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.aws_assume_role }}
          aws-region: ${{ secrets.aws_region }}

      - name: deploy lambda functon with image
        run: aws lambda update-function-code --function-name ${{ secrets.function_name }} --image-uri ${{ secrets.image }}