name: Update Argo App Config Version

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      deployment_type:
        type: string
        required: true
      app_name:
        type: string
        required: true
      version:
        type: string
        required: true
        description: Application version which is usually the github tag.

    secrets:
      gh_repo_write:
        required: true
        description: Token to be used to update argo app repository.

jobs:
  update_chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: trialstudio/argo_apps
          token: ${{ secrets.gh_repo_write }}
      - name: Update values file version
        run: |
          YQ_IN_PLACE_EDIT_PATH='.${{ inputs.deployment_type }}.app.version="${{ inputs.version }}"'
          VALUES_FILE=${{ inputs.deployment_type }}/${{ inputs.app_name }}/values-${{ inputs.environment }}.yaml
          
          docker run -v `pwd`/${VALUES_FILE}:/values.yaml mikefarah/yq -i "${YQ_IN_PLACE_EDIT_PATH}" /values.yaml

      - name: Commit update
        run: |
          git config --global user.email "github@actions.com"
          git config --global user.name "github-action"
          git add $VALUES_FILE 
          git commit -m 'Set ${{ inputs.app_name }} to ${{ inputs.version }} in ${{ inputs.environment }}'
          git push